// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMlJ4VwI9nsrKCGx4XBz-leq-nz_2OEwo',
    appId: '1:554423684365:web:85c48e7af45bd302f23444',
    messagingSenderId: '554423684365',
    projectId: 'learning-b305b',
    authDomain: 'learning-b305b.firebaseapp.com',
    storageBucket: 'learning-b305b.appspot.com',
    measurementId: 'G-HYH6XZ5C0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwA15X4e2gTSqZdDpX0saJ_Kvn1QYesnk',
    appId: '1:554423684365:android:1754c1446a66fb51f23444',
    messagingSenderId: '554423684365',
    projectId: 'learning-b305b',
    storageBucket: 'learning-b305b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnH6CY_EEXKtQDA9R8s9WzSHsWZPM6pIc',
    appId: '1:554423684365:ios:be020d07497bf447f23444',
    messagingSenderId: '554423684365',
    projectId: 'learning-b305b',
    storageBucket: 'learning-b305b.appspot.com',
    iosClientId: '554423684365-4u15ujrl0va3h7pd23i2cnjck3lbgt35.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnH6CY_EEXKtQDA9R8s9WzSHsWZPM6pIc',
    appId: '1:554423684365:ios:be020d07497bf447f23444',
    messagingSenderId: '554423684365',
    projectId: 'learning-b305b',
    storageBucket: 'learning-b305b.appspot.com',
    iosClientId: '554423684365-4u15ujrl0va3h7pd23i2cnjck3lbgt35.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningm',
  );
}
